= Example Manual 日本語
Doc Writer <doc.writer@example.org>
2017-09-22
:revnumber: {project-version}
:example-caption!:
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../java]
:stylesheet: style/asciidoctorｄ.css

This is a user manual for an example project.


== Introduction

本プロジェクトは、gradle環境でasciidoctor+diagramを利用するためのサンプルです。
includeしてる場合は、include先も監視対象とする必要あり。

=== LiveReloadの使い方

. 2つgitbashを立ち上げる
. それぞれ、./gradlew -t asciidoctor , ./gradlew live を実行する
. Live Reloadプラグインをchromeに導入し、ファイルをurlとしてアクセスにチェック
. ブラウザでbuild/asciidoc配下に生成されているhtmlを開き、Live Reloadのボタンを押下して有効にする。

=== スタイルの調整

. スタイルは、asciidoctor-stylesheet-factoryで生成する
.. fontを指定。
.. bodyを80%に縮小
.. リストのボトムを詰める(paragraphのボトム)
+
.リストは詰めすぎか？
[source,css]
----
//追加部分
$main-font-family: "源ノ明朝 JP", "游明朝", "メイリオ";
//$main-font-family: "MeiryoUI", "メイリオ";
$fixed-font-family: "Source Han Code JP";
$sans-font-family: "メイリオ", "游ゴシック";
//以下は効かない
//, "Noto Serif CJK JP", "Noto Sans CJK JP","源ノ角ゴシック", "Noto Sans Mono CJK JP"
$paragraph-margin-bottom: 0.2em;
----

=== 雑感
. WORDの使い方覚えるよりもAsciidocの記法を覚えるほうが楽である。
. asciidocのほうがwordより構造化しやすい。
. 欠点は、表や図が書きにくいこと。画像の貼り付けも以前作った *補助ツール* がやはり要る。

NOTE: 補助ツールは、ppt上の図をsvgで保存し、asciidoc内のリンクをクリップボードに生成する仕様だったはず。

[TIP]
--
* ≪要確認≫最下部の生成タイムスタンプ等のフッターがなければ、bracketsのライブリロードもうまくいくかも。
* gradle内の変数が使える
--

== Graphviz/DOT

.Graphviz 例1
[plantuml, graphviz, svg]
--
digraph foo {
    node [
        style=rounded,
        
    ]
    node1 [shape=box]
    node2 [fillcolor=yellow, style="rounded,filled", shape=diamond]
    node3 [shape=record, label="{ 日本語あ | b | c }"]

    node1 -> node2 -> node3
}

--


.Graphviz 例2
[plantuml, graphviz-a, svg]
--
digraph G {
    node [
        fontname = "MeiryoUI",
    ]
    rankdir=LR; 松->竹->梅ｄ
}
--

.Graphviz 例3
[plantuml, graphviz-b, svg]
--
digraph graph_name {
    edge [fontname = "Source Han Code JP"]
    node [
        shape = record,
        fontname = "Source Han Code JP",
        fontsize = 12,
    ]

    // node define
    alpha [label = "<pl>left|center|<pr>right"];
    beta [label = "<pl>left|<pc>center|<pr>right"];
    gamma [label = "left|center|<pr>right"];
    delta [label = "{left|{<pc>center|{top|middle|bottom}}|right}}"];
    epsilon [label = "{top|<pm>middle|bottom}"];

    // edge define
    alpha:pl -> beta:pl [ label = "a-b", weight = 2.0];
    alpha:pr -> gamma:pr [label = "a-g", weight = 1.0];
    beta:pc -> epsilon:pm [label = "b-e"];
    gamma -> delta:pc [label = "g-d"];
}
--


== Plantuml

.UML Diagram Example
[plantuml,uml-example ,svg]
--
skinparam defaultFontName "MeiryoUI"

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
  Object[] element日本語
  size()
}

enum TimeUnit {
  DAYS
  HOURS
  MINUTES
}

annotation SuppressWarnings
--

.クラス図
[plantuml, classediagram, svg]
....
skinparam defaultFontName "MeiryoUI"
class "クラスA" {
  +メソッド1ｄｄｄｄ()
}
class "クラスB" {
  +メソッド2()
}
class "クラスC" {
}
class "クラスD" {
}
class "クラスE" {
}
"クラスA" -- "クラスB"
"クラスA" <|-- "クラスC"
"クラスC" <|-- "クラスD"
"クラスC" <|-- "クラスE"
....


This project does something.
We just haven't decided what that is yet.

This page was built by the following command:

 $ ./gradlew asciidoctor


== Ditaa

You can make http://asciidoctor.org/docs/asciidoctor-diagram/[diagrams in Asciidoctor]

For example, the following:

.Basic ditaa block
[source]
----
[ditaa]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+


....
----

produces

.Basic ditaa block output
[ditaa]
----
                   +-------------+
                   | Asciidoctor |-------+
                   |  Diagram    |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /----------------\
 |        | --+ Asciidoctor +--> |                |
 |  Text  |   +-------------+    |Beautiful output|
 |Document|   |   !magic!   |    |                |
 |     {d}|   |   日本語       |    |                |
 +---+----+   +-------------+    \----------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+

/--------------------+                                    /------+ /------+
|                    |                                    |cBLK  | |cBLK  |
|                    | /--------------+ /---------------+ +------+ +------+
|       +------+     | |              | |               |
|       |      |     | |      +-------+ |               | +------+ +------+
|  cRED |      |     | |      |         |      +--------+ |      | |      |
|       +------+     | |      +-------+ |      |          |      | |      |
|                    | |              | |  cYEL|          |      | |      |
|                    | +--------+     | |      |          |      | |      |
|       +------+     |          |     | |      +--------+ |cBLK  | | cBLK |
|       |      |     | +--------+     | |               | |      | |      |
|       |      |     | |              | |               | |      | |      |
|       |      |     | |              | |               | |      | |      |
+-------+      +-----+ +--------------+ +---------------+ +------+ +------+
                       /--------------------+                   /------+
                       |                    |                   |      |
                       |                    |                   |      |
                       |       +------+     | /------+   +------+      +------+
                       |       |      |     | |      |   |        cYEL        |
                       |  cRED |      |     | |      |   +------+      +------+
                       |       +------+     | |      +--------+ |      |
                       |                    | |               | |      |
                       |       +------+     | |               | |      |
                       |       |      |     | |      +--------+ |      |
                       |       |      |     | |      |          |      |
                       |       |      |     | |      |          |      |
                       +-------+      +-----+ +------+          +------+

----

== build.gradle

[source,groovy]
----
include::{build-gradle}[]
----

